/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

import type {
  ColorTokenNormalized,
} from "@terrazzo/parser";

export declare const tokens: {
  "color.brand.50": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.100": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.200": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.300": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.400": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.500": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.600": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.700": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.800": Record<".", ColorTokenNormalized["$value"]>;
  "color.brand.900": Record<".", ColorTokenNormalized["$value"]>;
};

export declare function token<K extends keyof typeof tokens>(tokenID: K, modeName?: never): (typeof tokens)[K]["."];
export declare function token<K extends keyof typeof tokens, M extends keyof (typeof tokens)[K]>(tokenID: K, modeName: M): (typeof tokens)[K][M];
