/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "color.brand.50": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.9450980392156862,
        0.9490196078431372
      ],
      "alpha": 1,
      "hex": "#fff1f2"
    },
  },
  "color.brand.100": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8470588235294118,
        0.8588235294117647
      ],
      "alpha": 1,
      "hex": "#ffd8db"
    },
  },
  "color.brand.200": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7450980392156863,
        0.7686274509803922
      ],
      "alpha": 1,
      "hex": "#ffbec4"
    },
  },
  "color.brand.300": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.6352941176470588,
        0.6745098039215687
      ],
      "alpha": 1,
      "hex": "#ffa2ac"
    },
  },
  "color.brand.400": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.996078431372549,
        0.5215686274509804,
        0.5803921568627451
      ],
      "alpha": 1,
      "hex": "#fe8594"
    },
  },
  "color.brand.500": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#ff0000"
    },
  },
  "color.brand.600": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8313725490196079,
        0.2823529411764706,
        0.3843137254901961
      ],
      "alpha": 1,
      "hex": "#d44862"
    },
  },
  "color.brand.700": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6666666666666666,
        0,
        0.23529411764705882
      ],
      "alpha": 1,
      "hex": "#aa003c"
    },
  },
  "color.brand.800": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.4117647058823529,
        0,
        0.13333333333333333
      ],
      "alpha": 1,
      "hex": "#690022"
    },
  },
  "color.brand.900": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.20784313725490197,
        0,
        0.050980392156862744
      ],
      "alpha": 1,
      "hex": "#35000d"
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
