/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "color.brand.50": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.95,
        0.025,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.100": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.86,
        0.076,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.200": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.769,
        0.136,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.300": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.679,
        0.209,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.400": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.589,
        0.242,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.500": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.499,
        0.205,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.600": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.408,
        0.168,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.700": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.318,
        0.131,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.800": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.228,
        0.094,
        29.2
      ],
      "alpha": 1
    },
  },
  "color.brand.900": {
    ".": {
      "colorSpace": "oklch",
      "components": [
        0.168,
        0.065,
        29.2
      ],
      "alpha": 1
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
